### ISSUE TITLE
[Documentação] Inconsistencia classe Entidade

### ISSUE THREAD

**Issue by antuniooh** [antuniooh/Sistema-de-Judocas#5]
Não há o atributo endereço no diagrama de classes da entidade 

![image](https://user-images.githubusercontent.com/51217271/202877341-df38aaa8-4574-4daa-ba88-c72f5211a7dc.png)

**Comment by JoaoDias-223** [comment]
Como Entidade e Endereço estão conectados no diagrama, isso não é necessário.
