### ISSUE TITLE
[Documentação] Inconsistencia na classe professor

### ISSUE THREAD

**Issue by antuniooh** [antuniooh/Sistema-de-Judocas#9]
A classe não está no diagrama com os atributos presentes no código.

Além disso os metodos get e set de Entidades, não estão presentes. Quando for adicionado tmb deve haver a conexão entre as classes no diagrama

**Comment by JoaoDias-223** [comment]
Como as duas classes estão relacionadas, acho que não é necessário adicionar o get e o set de Entidades. Além disso, é por conta dessa relação que a classe Professor possui "menos atributos".
